image: Visual Studio 2017

environment:
  nodejs_version: "Current"

  matrix:
    - nodejs_arch: x86
    - nodejs_arch: x64

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
  - git submodule update --init
  - git apply --directory=dependencies/subversion ./dependencies/patches/subversion.diff
  - cd dependencies/subversion
  - python gen-make.py --with-zlib=../zlib --with-apr=../apr --with-apr-util=../apr --with-apr-iconv=../apr-iconv --with-sqlite=../sqlite-amalgamation --disable-shared --with-static-apr --vsnet-version=15 --disable-gmock
  - cd ../..

build_script: npm install

test: npm test

artifacts:
  - path: build/Release/svn.node
    name: Binary
    type: File
