image: Visual Studio 2017

environment:
  nodejs: "Current"

  matrix:
    - arch: x86
    - arch: x64

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs $env:arch
  - git submodule update --init

build_script: npm install

test_script:
  - npm test -- --reporter mocha-appveyor-reporter & exit 0

artifacts:
  - path: build/Release/svn.node
    name: Binary
    type: File
